
name: Build docker image

on:
  pull_request:
    branches: [ master, development ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '11'
      
      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run tests'
        run: npm run test

  build-docker-image:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository }}:latest
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{github.repository_owner}}/${{github.repository}}
          tag_with_ref: true