
name: Build docker image

on:
  push:
    branches: [ development ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '11'
      
      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run tests'
        run: npm run test

  build-docker-image:
    runs-on: ubuntu-latest
    needs: run-unit-tests

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          repository: ${{github.repository}}
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/coderscommunity/http-websocket-server:rc

